### ISSUE TITLE
Adhell has a lot of device administrator rights

### ISSUE THREAD

**Issue by pbochenski** [adhell/android#26]
Adhell requires a lot of administrative rights on device.
I think that they are mostly unnecessary.
[device-2017-05-18-092210](https://cloud.githubusercontent.com/assets/2960606/26190839/c1aaa6ea-3bab-11e7-910c-debbae6f7613.png)
[device-2017-05-18-092219](https://cloud.githubusercontent.com/assets/2960606/26190840/c1ab12a6-3bab-11e7-9552-ac4fbee4f97f.png)
[device-2017-05-18-092238](https://cloud.githubusercontent.com/assets/2960606/26190841/c1ab7020-3bab-11e7-9b1a-64f55c24ee51.png)
[device-2017-05-18-092251](https://cloud.githubusercontent.com/assets/2960606/26190838/c1a9e228-3bab-11e7-927b-110c5efe28ff.png)

**Comment by thefrenchmatt** [comment]
came here to ask the same...

**Comment by algorythmic** [comment]
C.f. 1.2.12, which requested only "Manage applications" and "Set device firewall"

![screenshot_20170522-190925](https://cloud.githubusercontent.com/assets/1232097/26332075/7ff8a56a-3f22-11e7-9e92-d23a5d1bc2d2.jpg)

**Comment by raiym** [comment]
Since app uses Samsung MDM instruments for blocking ads (Samsung Firewall in this case) and MDM only for corporate owned phones it wasn't created for B2C market and there is no way to give app with admin permission or reduce the amount of permissions that you see on admin page because they aren't atomic. At least I don't know the way to do it. 

It is one of reasons why project is open-source.

**Comment by pbochenski** [comment]
I don't know for sure, but one can probably limit it in file: ``https://github.com/adhell/android/blob/master/app/src/main/res/xml/enterprise_device_admin.xml`` as described here: ``https://developer.android.com/guide/topics/admin/device-admin.html``
